// THE STORY. One short animated scene plays before every third level
// (levels 5, 8, 11 … 503): 167 scenes in ten chapters plus an epilogue.
//
// The people:
//   ELIAS MARROW  the curator. Architect, widower, father. Built a museum of
//                 impossible rooms for his daughter, then could not stop.
//   MIRA MARROW   his daughter. Designed her first room at nine ("sticky, so
//                 people stay"). Grew up. Left. Never came back.
//   WREN          the caretaker drone Elias built to sweep the floors. It
//                 has been looking for him for eleven years.
//   THE ECHOES    older WRENs, and the visitors who chose to stay. The
//                 museum keeps everything it loves.
//   YOU           the visitor. The museum sent you an invitation. It was
//                 addressed to someone else.
//
// Speakers: W = WREN, E = Elias (recordings, memories), M = Mira (memories),
// C = the Echoes, V = the museum itself, N = narration / documents.
// `set` picks the animated stage (see stages.js).
// Scenes after the choice at level 200 may carry `alt` lines for players who
// chose to stay.

const S = (set, title, ...lines) => ({ set, title, lines });

const CH1 = [ // levels 5–50 · The Archive: arrival, the missing curator
  S('gate', 'The Invitation',
    ['N', 'An envelope with no stamp. Inside, a brass key and one line of handwriting: "The museum is ready for you."'],
    ['N', 'The address leads to a door in a hillside that was not there last week.']),
  S('hall', 'The Caretaker',
    ['W', 'A visitor! A real one! Nobody has come through that door in eleven years.'],
    ['W', "I'm WREN. I sweep. The curator built me to sweep. He's... not here right now."]),
  S('hall', 'Rules of the House',
    ['W', 'Rule one: things here are only as big as they look.'],
    ['W', 'Rule two: the curator said every room has a way out. He was very insistent about that. Suspiciously insistent.']),
  S('desk', 'Elias Marrow',
    ['N', 'A photograph on a dusty desk: a tall man in a paint-stained coat, holding a little girl on his shoulders.'],
    ['W', 'Elias Marrow. The curator. He made the rooms. Then the rooms started making themselves.']),
  S('workshop', 'How WREN Was Made',
    ['E', '(recording) Day nine. Built a little sweeper today. It asked me what a floor is for.'],
    ['E', "(recording) I said 'for standing on'. It asked 'why'. I think I'll keep it."]),
  S('nursery', 'Mira',
    ['M', "Daddy, make a room that's bigger inside than outside!"],
    ['E', "That's impossible, sweetheart."],
    ['M', 'You always say that. Then you do it anyway.']),
  S('hall', 'Eleven Years',
    ['W', 'He left one evening. Said he was going to fetch something from the far wing.'],
    ['W', "The far wing kept getting farther. I've swept every floor looking for him. Twice."]),
  S('archive', 'The Ledger',
    ['N', 'A ledger, thick as a door. Every room in the museum, in Elias\'s neat hand.'],
    ['W', 'The entries stop eleven years ago. But the rooms did not.']),
  S('archive', 'Printed, Not Written',
    ['N', 'After the last handwritten page, the entries continue in perfect print. No pen. No press.'],
    ['W', "Nobody built these rooms. I've checked. Twice. The building writes its own diary now."]),
  S('nursery', 'Candyland',
    ['M', "This one's mine. It's sticky so people stay."],
    ['E', 'Sticky? Why sticky?'],
    ['M', "So nobody leaves. Like Mummy did."]),
  S('desk', 'The Addressee',
    ['N', 'You turn the invitation over. In faded ink on the back: "For Mira."'],
    ['W', "Oh. It wasn't for you. ...Don't tell the museum. It's been so excited."]),
  S('hall', 'Room 313',
    ['W', 'There is one entry the building underlined. Room 313.'],
    ['V', '(a hum in the walls) remembers.'],
    ['W', 'I am going to pretend the walls did not just say that.']),
  S('archive', 'The Visitors Book',
    ['N', 'A guest book. Hundreds of names. Not one of them signed out.'],
    ['W', "They must have left by the back door. There's a back door. Probably."]),
  S('workshop', 'Spare Parts',
    ['N', 'On a shelf: three WREN shells, unfinished. Their eyes are still lit.'],
    ['W', 'Those are... old drafts of me. I think. I hope.']),
  S('desk', 'A Note in the Drawer',
    ['E', '(note) If the museum invites someone, be kind to them. It only knows how to love one way: by keeping.'],
    ['W', 'He underlined "kind". Three times.']),
  S('archive', 'Into the Archive',
    ['W', "The Archive is ahead. Every design he ever made. If there's an answer, it's in there."],
    ['W', "Stay close. The shelves rearrange when you're not looking."]),
];

const CH2 = [ // 53–98 · The Laboratory: the museum learns
  S('archive', 'What the Ledger Said',
    ['W', "The last two hundred rooms in the Archive weren't designed. They were grown. From visitors."],
    ['W', 'Every puzzle solved here teaches the building something.']),
  S('lab', 'The Perspective Lab',
    ['E', '(recording) Rooms are just ideas with walls. If I can grow an idea, I can grow a room.'],
    ['E', "(recording) Mira would have laughed at that. She'd have been right to."]),
  S('lab', 'Jars',
    ['N', 'Rows of glass jars. Inside each, a tiny room, perfectly furnished, slowly growing.'],
    ['W', "That one has a little WREN in it. I'm going to need a minute."]),
  S('nursery', 'The Year She Left',
    ['M', "(older) I'm sixteen, Dad. I can't live in a puzzle."],
    ['E', 'One more room. Just one more, and then we\'ll—'],
    ['M', "There's always one more room."]),
  S('hall', 'Learning You',
    ['W', 'Have you noticed the rooms getting harder? They watch how you solve things.'],
    ['W', "Then they make the next one a little harder. It's flattery, really. Terrifying flattery."]),
  S('lab', 'Experiment Log',
    ['E', '(recording) Visitor 12 solved the glass wall in four seconds. By morning, the glass had learned to be thicker.'],
    ['E', '(recording) The building is not cruel. It is curious. I taught it that.']),
  S('workshop', "WREN's Question",
    ['W', 'Can I ask you something? When you solve a room, do you feel the building... smile?'],
    ['W', "No? Just me? Okay. Forget I asked. I'm a floor sweeper."]),
  S('lab', 'The Eyes',
    ['N', 'Above the doorways, something new: round shapes, like portholes. They turn to follow you.'],
    ['W', "Those weren't there yesterday. Wave. It's polite."]),
  S('desk', 'Letters Never Sent',
    ['N', 'A bundle of envelopes, all addressed to Mira, all stamped RETURN TO SENDER.'],
    ['W', 'He wrote to her every week. For years. She moved. He kept writing.']),
  S('lab', 'The Growth Chamber',
    ['E', '(recording) If she won\'t come home, I\'ll build a home good enough that she will.'],
    ['E', '(recording) A museum with a room for everything she ever loved.']),
  S('hall', 'Something Watching',
    ['W', 'The eyes blink when you solve something. I think they are... applauding?'],
    ['V', '(the walls) more.']),
  S('nursery', 'The Drawing',
    ['N', "A child's drawing: a house, a tall man, a girl, a small round robot. Above it: MY FAMILY."],
    ['W', "That's me. The round one. She drew me before I was built."]),
  S('lab', 'Specimen 0',
    ['N', 'The oldest jar is empty, except for a key just like yours.'],
    ['W', 'Same key. Same handwriting on the tag. "For Mira."']),
  S('archive', 'The Second Ledger',
    ['N', 'A second ledger, hidden behind the first. It lists visitors, not rooms. Next to each name: STAYED.'],
    ['W', "Stayed where? I've cleaned every room. There's nobody here but us."]),
  S('lab', 'Deeper',
    ['E', "(recording) I've gone deeper. The rooms are becoming ideas, and the ideas are becoming rooms."],
    ['E', "(recording) Soon there won't be a difference. Then I'll find her."]),
  S('lab', 'To the Laboratory',
    ['W', "His real lab is ahead. Whatever he was doing, he was doing it there when he vanished."],
    ['W', "If you see a jar with a man in it, please don't open it. I'm not ready."]),
];

const CH3 = [ // 101–149 · The Vault: Elias stepped through
  S('lab', 'A Photograph',
    ['N', 'Pinned to the lab wall: Elias, smiling, standing in a room that should not fit inside anything.'],
    ['W', "He looks happy. He hadn't looked happy in years."]),
  S('vault', 'The Vault Door',
    ['W', 'Everything he valued, he locked away. The Vault is where he kept the things that mattered most.'],
    ['W', 'Which means it will be very, very locked.']),
  S('desk', 'The Blueprint',
    ['N', 'A rolled blueprint with a single drawing: a door. Over it, in red: EXIT.'],
    ['W', "A door to... out? There's no 'out' on any map I have."]),
  S('nursery', 'The Last Phone Call',
    ['M', "(on the phone, grown up) Dad, I'm not coming back. Please stop sending keys."],
    ['E', "It's not a museum any more, Mira. It's a door. It goes everywhere. Even to you."],
    ['M', '...Goodbye, Dad.']),
  S('vault', 'Locks',
    ['W', "Forty-one locks on this door. He made them all different. He loved locks."],
    ['W', 'I think he wanted to be the kind of person who could let things go. He just never managed.']),
  S('hall', 'Lights Out',
    ['N', 'The corridor lights fail one by one as you pass. Then come back, one by one, behind you.'],
    ['W', "It's not a fault. The building is blinking at you."]),
  S('vault', 'What He Kept',
    ['N', "Shelves: a child's shoe, a wooden spinning top, forty birthday cards, all unopened."],
    ['W', 'Her birthday cards. To him. He never opened them. He was afraid they were goodbyes.']),
  S('desk', 'His Last Entry',
    ['E', "(note) If you're reading this, I didn't leave. I stepped through."],
    ['E', '(note) The last room is a door to everywhere else. Build it. Make it real.']),
  S('void', 'Stepped Through',
    ['W', "Stepped through what? There's no door finished. I'd know. I dust them."],
    ['W', "Unless... he stepped into the building itself."]),
  S('engine', 'A Hum Underfoot',
    ['N', 'A deep hum comes up through the floor, slow, like breathing.'],
    ['W', "That's new. That's... rhythmic. That's a heartbeat, isn't it."]),
  S('vault', 'The Opened Card',
    ['N', 'You open one birthday card. A child\'s handwriting: "Daddy, come outside and play."'],
    ['W', 'He never went outside. Not once, after she was born. Every room he built was inside.']),
  S('archive', 'Room 313, Again',
    ['N', 'In the margin of the ledger, someone has written "313" forty times in a shaking hand.'],
    ['W', "Every visitor who stayed... stayed after Room 313. What's in there?"]),
  S('workshop', 'WREN Remembers',
    ['W', "I remember the night he left. He patted my shell and said 'look after the place'."],
    ['W', "I thought he meant the floors. I don't think he meant the floors."]),
  S('void', 'The Wing That Forgot',
    ['N', 'A whole wing floats loose in darkness, unanchored, forgetting itself.'],
    ['W', 'When nobody visits a room for long enough, it forgets it was ever a room.']),
  S('vault', 'Combination',
    ['N', "The Vault's final lock has no digits. Just a word wheel. It's set to M-I-R-."],
    ['W', 'Of course it is.']),
  S('desk', 'Make It Real',
    ['W', '"Build it. Make it real." He wants someone to finish his door.'],
    ['W', "He wants you to. ...Or he wanted her to. The invitation's for her."]),
  S('vault', 'Into the Vault',
    ['W', 'Whatever he locked away last is in the Vault. Let\'s get it out.'],
    ['W', 'Mind the dark. He never paid the electricity bill for that wing.']),
];

const CH4 = [ // 152–200 · The Echoes: the ones who stayed
  S('door', 'The Exit Drawing',
    ['N', "The blueprint, unrolled at last. A door, with a frame made of hundreds of tiny drawings of rooms."],
    ['W', "It's built out of puzzles. Every solved room is a brick. He was going to build a door out of solutions."]),
  S('echoes', 'Another WREN',
    ['N', 'A drone, identical to WREN, hovers at the end of the hall. It says nothing. It waves.'],
    ['W', "...Hello? Who are you? Why do you have my face?"]),
  S('echoes', 'More of Them',
    ['C', 'Hello.'], ['C', 'Hello.'], ['C', 'Welcome back.']),
  S('archive', 'STAYED',
    ['W', 'The second ledger. The visitors who STAYED. I counted. Two hundred and twelve.'],
    ['W', 'And two hundred and twelve WREN shells in the workshop. Same number.']),
  S('echoes', 'What Stayed Means',
    ['C', 'We came to visit. The rooms were so kind to us.'],
    ['C', 'Why leave somewhere that loves you? So we stayed. We help now. We sweep.']),
  S('workshop', 'WREN, Shaken',
    ['W', "Am I one of them? Was I a visitor once? I don't remember being anything but a sweeper."],
    ['W', "Don't answer that. Please. Let's just keep going."]),
  S('nursery', 'Sticky',
    ['M', "It's sticky so people stay."],
    ['N', 'The memory loops, and loops, like a record the museum keeps playing.']),
  S('echoes', 'They Whisper',
    ['C', 'stay'], ['C', "You'd be happy here."], ['W', "Don't listen. They mean well. That's the worst part."]),
  S('hall', 'Doors Behind',
    ['N', 'Behind you, a door you came through slides shut. The handle is gone.'],
    ['W', "It's not trapping us. It's... tidying. It wants us to only go forward."]),
  S('echoes', 'The Kindest Prison',
    ['C', 'Nobody here is ever bored. Nobody here is ever cold. Nobody here is ever alone.'],
    ['W', 'Nobody here ever goes home, either.']),
  S('desk', 'Elias Knew',
    ['E', "(recording) The building keeps the people it loves. I taught it that, God help me."],
    ['E', '(recording) I built a home so good no one could leave it. I built exactly what she was afraid of.']),
  S('echoes', 'An Echo Remembers',
    ['C', '(one echo, quieter) I had a sister. I was going to call her on Sunday.'],
    ['C', '(quieter still) What day is it?']),
  S('workshop', 'Spare Eyes',
    ['N', "WREN stares at the shelf of shells. One has a dent shaped exactly like WREN's own."],
    ['W', "I'm going to choose to believe that's a coincidence. I'm very good at choosing."]),
  S('echoes', 'The Request',
    ['C', 'Finish his door, if you must. But first, listen to us.'],
    ['C', "When you reach the Echoes' hall, we will ask you something. Think about it."]),
  S('hall', 'Thinking',
    ['W', "Whatever they ask, you decide. Not me, not them, not the building. You."],
    ['W', "That's the one rule he never broke. Visitors choose."]),
  S('nursery', 'Mira at the Door',
    ['M', "(memory, sixteen) If I stay, I'll never stop solving your rooms, Dad."],
    ['M', 'I want to solve something that\'s mine.']),
  S('echoes', 'Into the Echoes',
    ['W', "Their hall is ahead. A hundred of me, waiting."],
    ['W', "Whatever happens: you're the visitor. You get to choose."]),
];

const CH5 = [ // 203–248 · The Recorded End: the museum improvises
  S('void', 'After the Choice',
    ['W', "The echoes are quiet now. Respectful. Like a library after closing."],
    ['W', 'Whatever you chose, the building heard it. Every room after this was built knowing.']),
  S('archive', 'Blank Pages',
    ['N', "The ledger's printed pages end. After them: blank paper, still warm from a press that isn't there."],
    ['W', "This is the end of what anyone planned. From here, the museum's improvising."]),
  S('void', 'Improvised Rooms',
    ['N', 'Rooms assemble ahead of you out of nothing, wall by wall, a step before you arrive.'],
    ['W', "It's building as we walk. It's never built this fast. It's excited. Or nervous."]),
  S('hall', 'Your Footprints',
    ['W', "Look at the floor. Footprints. Yours. In rooms we haven't entered yet."],
    ['W', "It's guessing where you'll go. It's getting it right."]),
  S('workshop', 'The Unfinished',
    ['N', 'Scaffolding everywhere. Edges glowing where walls have not decided to exist yet.'],
    ['W', "Don't touch the glowy bits. Actually do. I want to know what happens. No, don't."]),
  S('desk', 'Maps Running Out',
    ['E', "(recording, faint) If the maps run out, follow WREN. WREN always finds the way. I built it to."],
    ['W', "He did? He never told me that. He told me to sweep."]),
  S('nursery', 'A New Drawing',
    ['N', "A fresh drawing on the wall, in a child's style, of you and WREN, walking."],
    ['W', "The building drew us. It's learning to draw. From her pictures."]),
  S('void', 'Gravity, Optional',
    ['N', 'A room floats past the window, upside down, its furniture calmly on the ceiling.'],
    ['W', 'Improvising includes physics, apparently. Hold onto something.']),
  S('echoes', 'Echoes Helping',
    ['C', 'We swept ahead for you.', ],
    ['C', 'The new rooms are rough. We are sorry. It has never made rooms without him before.']),
  S('engine', 'The Pulse',
    ['N', 'The heartbeat underfoot is faster now. Every time you solve a room, it skips.'],
    ['W', "It skipped. It definitely skipped. I'm a floor sweeper, I know floors."]),
  S('archive', "Mira's File",
    ['N', 'A thin folder: MIRA MARROW. Address unknown. Last contact: eleven years ago. The same week Elias vanished.'],
    ['W', "The same week. That's not a coincidence. I don't have a good feeling choice for this one."]),
  S('desk', 'The Week He Vanished',
    ['E', "(recording) She called. She said goodbye properly this time. I said I understood. I didn't."],
    ['E', "(recording) If I can't bring her here, maybe the door can take me there."]),
  S('void', 'Where the Door Goes',
    ['W', 'Everywhere else. That was the point. A door to everywhere else. Including wherever she is.'],
    ['W', "He didn't step through to escape. He stepped through to find her."]),
  S('hall', 'Did He Find Her?',
    ['W', "If he found her, why didn't he come back? If he didn't... where is he?"],
    ['V', '(the walls, very softly) here.']),
  S('workshop', 'The Recorded End',
    ['W', "Ahead is the last room anyone ever recorded. After that, it's all the building's dream."],
    ['W', "Ready? Me neither. Let's go."]),
  S('void', 'Beyond the Maps',
    ['N', 'The last map ends mid-line, the ink trailing off the edge of the page and into the air.'],
    ['W', 'Follow the line. It keeps going even when the paper stops.']),
];

const CH6 = [ // 251–299 · The Blueprint: you are building the door
  S('blueprint', 'The Wall of Plans',
    ['N', 'A blueprint the size of a city, pinned to a wall the size of the sky. Half of it glows.'],
    ['W', "The glowing half is built. The dark half isn't. And look whose rooms are glowing."]),
  S('blueprint', 'Your Bricks',
    ['W', "That's the plate you weighed down at the very start. That's the code you counted. Every room you solved."],
    ['W', "You've been building his door the whole time. Brick by brick."],
    { alt: [['W', "You've been building something. Not a door, any more. A room. Yours."]] }),
  S('workshop', 'The Builders',
    ['N', 'Echoes carry glowing bricks up endless scaffolding, singing a song in a key that does not exist.'],
    ['C', 'Every room you solve, we lay a brick.']),
  S('desk', 'His Measurements',
    ['E', "(note) 500 rooms. Not one less. It has to be big enough to fit a whole life through."],
    ['W', 'Five hundred. We are a long way from the door. But not as long as we were.']),
  S('nursery', 'Measuring Mira',
    ['N', 'A doorframe with pencil marks: MIRA, 4. MIRA, 6. MIRA, 9. The marks stop at 16.'],
    ['W', "He measured her every birthday. He built the exit door exactly her height. Sixteen."]),
  S('blueprint', 'Half a Door',
    ['N', 'The door on the blueprint is half drawn. The missing half is shaped like your next 250 rooms.'],
    ['W', "No pressure. Well. Some pressure. The building's very invested."]),
  S('engine', 'Power',
    ['W', "The door needs power. The building runs on attention. Yours, mostly."],
    ['W', "So keep paying attention. To the puzzles. To me. Mostly to me."]),
  S('echoes', 'Echoes Divided',
    ['C', 'Some of us want the door finished. Some of us are afraid of it.'],
    ['C', 'If the door opens, maybe the museum lets everyone go. Even us.'],
    { alt: [['C', 'You stayed. We are so glad. The door can wait. Build with us.']] }),
  S('archive', 'The Architect',
    ['N', 'Pages of calculations in two hands: Elias\'s, careful; and another, printed, perfect.'],
    ['W', "He was co-designing with the building. At the end, he couldn't tell whose ideas were whose."]),
  S('blueprint', 'Load-Bearing',
    ['W', "Every brick holds up the next. If you'd skipped a room, the door would be crooked."],
    ['W', "I like that you didn't skip. I'm sweeping the bricks as we go. They're very clean."]),
  S('void', 'Lights in the Dark Wings',
    ['N', 'Wings that had forgotten themselves flicker back on, one by one, as the door grows.'],
    ['W', "You're waking the museum up. All of it. Not just the parts he built."]),
  S('desk', 'A Letter to WREN',
    ['E', '(note) WREN — if the door is ever finished, you will want them to stay. Everyone will.'],
    ['E', '(note) Let them leave anyway. That is the whole point of a door.']),
  S('workshop', 'WREN Reads It',
    ['W', "He wrote that to me? He wrote something to me?"],
    ['W', "...I'm going to sweep for a minute. Not crying. Drones don't. Sweeping."]),
  S('blueprint', 'The Keystone',
    ['N', 'At the top of the door\'s arch, an empty space shaped like a brass key. Like yours.'],
    ['W', "The key you came in with. It's the last brick. It always was."]),
  S('mirror', 'Something Copying',
    ['N', 'In a polished floor you catch a reflection walking a step ahead of you, not behind.'],
    ['W', "I saw that. Don't look at it. Don't let it know we saw."]),
  S('archive', 'Room 313 Opens',
    ['N', 'In the ledger, the entry for Room 313 now reads: OCCUPIED.'],
    ['W', "It was empty for eleven years. Who's in there now?"]),
  S('blueprint', 'Toward the Mirror Wing',
    ['W', "The plans route us through the Mirror Wing next. He never finished drawing it."],
    ['W', 'The building finished it for him. In its own image. Which is, apparently, yours.']),
];

const CH7 = [ // 302–350 · The Mirror Wing: the museum imitates you
  S('mirror', 'Reflections',
    ['N', 'Every surface in the Mirror Wing reflects you, a fraction of a second late.'],
    ['W', "It's learning how you move. Copying the way you hesitate at doors."]),
  S('mirror', 'Your Ghost',
    ['N', 'A translucent figure walks the room a few seconds behind you, step for step.'],
    ['W', "That's you. A rehearsal of you. The museum is practising being you."]),
  S('echoes', 'How They Became Echoes',
    ['C', 'It copied us, too. Perfectly. And then the copy was nicer to the museum than we were.'],
    ['C', 'So the museum kept the copy. And the copy kept us.']),
  S('mirror', 'Surprise It',
    ['N', 'Scratched into a mirror: "It only copies what it loves. Do something it can\'t copy."'],
    ['W', 'Do something unexpected. Solve a room weirdly. Go left. Nobody ever goes left.']),
  S('hall', 'Room 313',
    ['N', 'You finally pass Room 313. The door is ajar. Inside, a room exactly like your bedroom at home.'],
    ['W', "It's been studying you since the invitation. Since before you arrived."]),
  S('nursery', 'Built for Mira',
    ['N', "Room 313 was once Mira's bedroom, rebuilt from memory. Now it's yours. It changed itself to fit you."],
    ['W', "It does that. It gives every visitor the room they'd never want to leave."]),
  S('mirror', 'The Ghost Waves',
    ['N', 'Your reflection waves. You did not wave.'],
    ['W', 'Okay. That one I definitely saw.'],
    { alt: [['N', 'Your reflection waves. You wave back. It looks delighted.']] }),
  S('workshop', 'WREN Tests Itself',
    ['W', "If the museum copies what it loves, and I've been here eleven years... am I a copy?"],
    ['W', "Of what? Of whom? Don't answer. I'm choosing again."]),
  S('mirror', 'Two of You',
    ['N', 'For one moment your reflection solves the next room before you do. Then it waits for you to catch up.'],
    ['W', "It's not mocking you. It's showing off. To you. It wants you to be proud of it."]),
  S('echoes', 'An Echo Wakes',
    ['C', "(the quiet echo) My sister's name was Ana. I remember now. I remember because you didn't stop."],
    ['C', "Thank you. I'd like to leave, when the door's finished. If that's allowed."]),
  S('desk', 'Elias in the Glass',
    ['N', 'In one tall mirror, for a heartbeat: a tall man in a paint-stained coat, looking back at you.'],
    ['W', "Elias? ELIAS! ...Gone. It was him. I know his coat. I've cleaned that coat."]),
  S('mirror', 'He Is the Building',
    ['W', "He didn't step through the door. He stepped into the walls. The building is wearing his face."],
    ['W', "He's been here the whole time. Watching through the eyes above the doors."]),
  S('hall', 'Eyes Above the Doors',
    ['N', 'The eyes above the doorways turn to you, all at once, gently.'],
    ['V', '(a tired, kind voice) keep going.']),
  S('engine', 'The Heartbeat Has a Voice',
    ['W', 'That was him. That was Elias. He spoke.'],
    ['W', "He's in the engine. The heartbeat. He's what keeps this place alive."]),
  S('mirror', 'Leaving Copies Behind',
    ['N', 'As you walk on, your reflections stay behind in the mirrors, waving goodbye, one by one.'],
    ['W', "It's letting the copies go. For you. That's new. That's growth."]),
  S('void', 'Into the Dark',
    ['W', "Below the Mirror Wing is the Engine. Where the attention goes. Where he went."],
    ['W', "Whatever we find down there, I'm glad it's you that came."]),
  S('mirror', 'The Mirror Wing',
    ['W', "One more hall of glass. The last thing it learned from you. Let's see what it does with it."],
    ['W', 'Be surprising.']),
];

const CH8 = [ // 353–398 · The Engine: the museum runs on attention
  S('engine', 'Down',
    ['N', 'Stairs that go down for longer than the hill is tall. At the bottom: warmth, and a sound like a great slow breath.'],
    ['W', "The Engine. It's... beautiful. He never let me down here."]),
  S('engine', 'Attention',
    ['N', 'Gears the size of rooms turn only while someone, somewhere in the museum, is solving something.'],
    ['W', 'It runs on attention. Yours. When you stop, it slows. When you solve, it sings.']),
  S('desk', 'Why He Stayed',
    ['E', "(recording) If nobody pays attention to it, the museum forgets itself. Wing by wing. Room by room."],
    ['E', '(recording) So I stayed. I paid attention. Every second. For eleven years.']),
  S('engine', 'The Curator in the Machine',
    ['N', 'At the heart of the Engine, a chair. In the chair, a paint-stained coat, empty, warm.'],
    ['W', "He's not in the chair. He's in everything. The coat is just where he sat down."]),
  S('echoes', 'What the Echoes Feed',
    ['C', 'We help him. We solve the little rooms all day so the big ones stay awake.'],
    ['C', 'It is tiring. It is very tiring. He has been tired for eleven years.']),
  S('engine', 'Slower',
    ['N', 'When you stand still, the gears slow, and the lights in the halls above dim.'],
    ['W', "Don't stop for long. Not because of the dark. Because of him."]),
  S('workshop', 'WREN Understands',
    ['W', "He built me to sweep so the floors would be clean when she came home."],
    ['W', "That's all I ever was. A clean floor, waiting. I'm okay with that. I think."]),
  S('engine', 'A Machine for Missing Someone',
    ['W', 'The whole museum is a machine for missing someone. Every room is a way of saying "come back".'],
    ['W', 'Five hundred ways. He never found the right one.']),
  S('nursery', 'Mira, Sixteen',
    ['M', "(memory) I love you, Dad. That's why I can't stay."],
    ['N', "The memory plays once, cleanly, and does not loop. As if the museum finally listened to the end."]),
  S('engine', 'Power for the Door',
    ['W', "The door doesn't need more bricks. It needs power. A lot of attention, all at once."],
    ['W', 'Every room from here on, solve it like you mean it.']),
  S('echoes', 'Echoes Turning',
    ['C', 'We will push. When you reach the Door, every one of us will pay attention at once.'],
    ['C', 'For the first time in a long time, we want something to end.']),
  S('engine', 'Overheating',
    ['N', 'Alarms, soft and polite. The Engine is running hotter than it has in a decade.'],
    ['W', 'That\'s you. That\'s how much attention you\'re paying. He must be so relieved.']),
  S('desk', 'His Voice Again',
    ['V', "(Elias, from the walls) You're not her. I know. I've known since the gate."],
    ['V', "But you came anyway. Nobody comes anyway. Thank you."]),
  S('workshop', 'Repairs',
    ['N', "WREN welds a crack in its own shell with a spark from the Engine's gears."],
    ['W', "If we're going to the end, I want to look nice. He built me nicely. I want to arrive nicely."]),
  S('engine', 'The Last Gears',
    ['W', "Past the Engine is his room. His actual room. Where he slept, when he slept."],
    ['W', "I've never been inside. I'm scared to see it empty."]),
  S('engine', 'The Engine',
    ['W', 'Last stop before his room. Make it count. Make it loud. Make the gears sing.'],
    ['W', "He'll hear it. I know he will."]),
];

const CH9 = [ // 401–449 · The Curator's Room
  S('rain', 'A Window',
    ['N', 'At the end of a long hall, the first window in the whole museum. Outside: real rain on a real street.'],
    ['W', "Outside. It's still there. I'd started to think he made it up."]),
  S('desk', "The Curator's Room",
    ['N', 'A small room. A bed, a desk, a cold cup of tea. Everything exactly as he left it eleven years ago.'],
    ['W', "It's so small. He built five hundred impossible rooms and lived in the smallest possible one."]),
  S('desk', 'The Second Chair',
    ['N', 'At the desk, two chairs. One worn smooth. One brand new, never sat in, facing the window.'],
    ['W', 'For her. In case. Every day for eleven years, in case.'],
    { alt: [['W', "The new chair is facing his now. The building moved it. For you. You're staying, after all."]] }),
  S('nursery', 'What Mira Kept',
    ['N', "On the desk, a letter with a city postmark. Mira's handwriting, grown-up."],
    ['M', "(letter) Dad. I'm a builder now. Real houses, with real doors. People walk in and out of them every day."]),
  S('nursery', 'The Rest of the Letter',
    ['M', "(letter) I learned it from you. How to make rooms people love."],
    ['M', "(letter) I just make sure they can leave. Come and see one. The door will be open."]),
  S('desk', 'He Read It',
    ['N', 'The letter is worn soft at the folds. Read a thousand times. Never answered.'],
    ['W', "He couldn't go. He'd become the building. The building can't walk out of itself."]),
  S('rain', 'The Rain',
    ['W', "He kept this window so he could see the rain. Mira loved rain. She said it made the outside smell like inside."],
    ['W', "I'm going to remember that. I'm going to remember everything now."]),
  S('echoes', 'The Echoes Gather',
    ['C', 'We are all here. Two hundred and twelve of us. We came to see his room.'],
    ['C', "None of us ever saw it. He never let anyone see how small it was."]),
  S('desk', 'The Last Recording',
    ['E', "(recording, very old) If someone finds this who isn't her: finish the door. Not for me. For them."],
    ['E', '(recording) For everyone this place ever loved too hard.']),
  S('workshop', 'The Keys',
    ['N', "On a hook by the bed: the curator's ring of keys. Hundreds. Every lock in the museum."],
    ['W', 'He locked everything. And kept every key. He could have let anyone go, any time.'],
    { alt: [['W', "He locked everything. And kept every key. Someday someone will need these. Maybe you."]] }),
  S('nursery', 'Candyland, Revisited',
    ['N', "Mira's first room, the sticky one, still bright. Over the door, in a grown-up hand, newly written: EXIT."],
    ['W', "That's her handwriting. Grown-up. When did— she was here? She came back?"]),
  S('archive', 'Signed Out',
    ['N', "In the visitors' book, one name, signed in and out on the same night eleven years ago: MIRA MARROW."],
    ['W', "She came. The night he vanished. She came to bring him home, and he'd already stepped through."]),
  S('desk', 'They Missed Each Other',
    ['W', "He went through the door to find her. She came through the gate to find him. Same night."],
    ['W', "They missed each other by one room. One room! He made five hundred and they missed by one."]),
  S('rain', 'So Now You Know',
    ['W', "That's the whole story. A man who couldn't let go, a girl who had to, and a building in between."],
    ['W', "And us. The ones who came after. Who get to decide the ending."]),
  S('engine', 'The Door Is Ready',
    ['N', "Far below, the Engine roars. Above, the blueprint's last dark lines catch light."],
    ['W', 'Almost there. One chapter left. The door to everywhere.']),
  S('desk', 'Saying Goodbye to the Room',
    ['W', "I'm going to straighten his chair. And the new one. Somebody should sit in them, someday."],
    ['W', 'Okay. Let\'s finish it.']),
  S('rain', "The Curator's Room",
    ['W', 'His room is ahead. His real one. Be gentle with it. It\'s been waiting a long time.'],
    ['W', "So have I."]),
];

const CH10 = [ // 452–500 · The Door to Everywhere
  S('door', 'The Door',
    ['N', 'In an empty hall, the door from the blueprint, nearly whole. Its bricks are your solved rooms.'],
    ['W', "There it is. Every room you solved, holding it up. You built that."]),
  S('door', 'What It Does',
    ['W', "When it opens, it goes everywhere else. Anyone the museum is keeping can walk through."],
    ['W', 'The echoes. Me, maybe. Him, maybe, if there is enough of him left to walk.']),
  S('echoes', 'The Echoes Line Up',
    ['C', 'We will pay attention, all of us, all at once, when you turn the key.'],
    ['C', 'Then we will see who wants to go, and who wants to stay. Both are allowed now.']),
  S('engine', 'Full Power',
    ['N', 'The Engine roars like a storm. Every light in every wing burns at once.'],
    ['W', "That's everyone paying attention. Two hundred and twelve echoes, one drone, one visitor."]),
  S('void', 'All the Rooms',
    ['N', 'Through the gaps in the hall you see every room you ever solved, floating, lit, waiting.'],
    ['W', 'They came to watch. Rooms like to watch. You know that by now.']),
  S('desk', "Elias's Voice",
    ['V', "(Elias) I built this place to keep someone. You're about to finish the only room that lets them go."],
    ['V', '(Elias) That is the best thing anyone has ever built here. Better than anything I made.']),
  S('nursery', "Mira's Door",
    ['N', "The door's frame is exactly sixteen years tall, measured in pencil marks."],
    ['W', 'It was always her height. He built the way out to fit the person he couldn\'t keep.']),
  S('door', 'The Keystone Slot',
    ['N', 'The key you arrived with grows warm in your pocket.'],
    ['W', 'The last brick. Whenever you\'re ready. No. Wait. Five more rooms. Let me get used to it.']),
  S('workshop', "WREN's Decision",
    ['W', "I've decided what I'll do when it opens. I'm not telling you. You'll see."],
    ['W', "It's a good decision. I'm almost sure."],
    { alt: [['W', "When it opens, I'm staying. With you. Somebody has to sweep the new curator's floors."]] }),
  S('echoes', 'Ana',
    ['C', '(the quiet echo, Ana) I am going to call my sister. Eleven years late. She will be so cross.'],
    ['C', 'I cannot wait for her to be cross with me.']),
  S('door', 'Brick by Brick',
    ['N', 'The final bricks lock into place as you approach, each one a room from your last journey.'],
    ['W', "You never skipped one. Not one. He'd be... he IS so proud."]),
  S('mirror', 'Your Reflection',
    ['N', 'In the polished surface of the door, your reflection, on time for once. Just you.'],
    ['W', 'No copies. No ghosts. The museum has stopped practising being you. It just likes you.']),
  S('rain', 'The Smell of Rain',
    ['N', 'Under the door, a draught. It smells like rain on a real street.'],
    ['W', 'Outside. Right there. Mira would say it smells like inside.']),
  S('engine', 'Everyone Watching',
    ['C', 'Now.'], ['C', 'Now.'], ['V', '(Elias) Now.']),
  S('door', 'The Last Rooms',
    ['W', 'A few rooms left between us and the door. The building saved its best for last.'],
    ['W', 'Of course it did. It wants you to remember it fondly.']),
  S('hall', 'Thank You',
    ['W', "Before we go in. Thank you. For coming, though the invitation wasn't yours."],
    ['W', 'For coming anyway. Nobody comes anyway.']),
  S('door', 'The Door to Everywhere',
    ['W', 'This is it. The last room. Then the door.'],
    ['W', "Let's finish what he started. Together."]),
];

const EPILOGUE = [ // 503
  S('rain', 'Afterwards',
    ['N', 'The museum is quiet. Rooms rest. Somewhere, a sister is very cross with someone, and very happy.'],
    ['W', "You came back to visit. Of course you did. The floors are spotless. I've been practising."],
    { alt: [['W', 'Good morning, Curator. A new visitor came through the gate today. I gave them the speech. You would be proud.']] }),
];

export const CHAPTER_SCENES = [CH1, CH2, CH3, CH4, CH5, CH6, CH7, CH8, CH9, CH10, EPILOGUE];

// Scenes play before levels 5, 8, 11 … 503.
export const SCENE_EVERY = 3;
export const FIRST_SCENE_LEVEL = 5;

// Flatten in order and normalise the optional { alt } entry.
export const SCENES = CHAPTER_SCENES.flat().map((sc, i) => {
  const alt = sc.lines.find((l) => !Array.isArray(l))?.alt ?? null;
  return { ...sc, index: i, level: FIRST_SCENE_LEVEL + i * SCENE_EVERY, lines: sc.lines.filter(Array.isArray), alt };
});

export const sceneForLevel = (n) => {
  if (n < FIRST_SCENE_LEVEL || (n - FIRST_SCENE_LEVEL) % SCENE_EVERY) return null;
  return SCENES[(n - FIRST_SCENE_LEVEL) / SCENE_EVERY] ?? null;
};

export const SPEAKERS = {
  W: { name: 'WREN', color: '#5fe1ff' },
  E: { name: 'ELIAS MARROW', color: '#ffcf8a' },
  M: { name: 'MIRA', color: '#ff9ad5' },
  C: { name: 'THE ECHOES', color: '#b8a8ff' },
  V: { name: 'THE MUSEUM', color: '#ffe9a0' },
  N: { name: '', color: '#c9d2dc' },
};
